version: "3.9"

services:
  prometheus:
    image: prom/prometheus:v2.50.1
    container_name: bo-prometheus
    network_mode: "host"
    volumes:
      - ./docker/observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./docker/observability/alert_rules.yml:/etc/prometheus/alert_rules.yml:ro

  grafana:
    image: grafana/grafana:10.3.1
    container_name: bo-grafana
    network_mode: "host"
    volumes:
      - ./docker/observability/grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      - ./docker/observability/grafana-dashboard-provisioning.yml:/etc/grafana/provisioning/dashboards/dashboard.yml:ro
      - ./docker/observability/grafana-dashboard.json:/etc/grafana/provisioning/dashboards/bo-dashboard.json:ro
